# Generated by Django 5.2.4 on 2025-07-28 17:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lat",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Latitude"
                    ),
                ),
                (
                    "lang",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Langitude"
                    ),
                ),
                (
                    "alt",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="altitude (elevation above sea level) (optional)",
                    ),
                ),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, geography=True, null=True, srid=4326
                    ),
                ),
            ],
            options={
                "verbose_name": "موقعیت مکانی",
                "verbose_name_plural": "موقعیت های مکانی",
            },
        ),
        migrations.CreateModel(
            name="FireStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="نام آتش نشانی",
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس"),
                ),
                (
                    "manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="manager",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مدیر",
                    ),
                ),
                (
                    "staffs",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="اعضای آتش نشانی",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.location",
                        verbose_name="موقعیت مکانی",
                    ),
                ),
            ],
            options={
                "verbose_name": "آتش نشانی",
                "verbose_name_plural": "آتش نشانی ها",
            },
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "inspection_created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاریخ تعریف بازرسی"
                    ),
                ),
                (
                    "warning_report",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "نرمال, پتانسیل خطر کم و قابل پذیرش",
                                "نرمال, پتانسیل خطر کم و قابل پذیرش",
                            ),
                            (
                                "متوسط, پتانسیل خطر متوسط و قابل پذیرش",
                                "متوسط, پتانسیل خطر متوسط و قابل پذیرش",
                            ),
                            (
                                "بالا, پتانسیل خطر بالا و غیرقابل پذیرش",
                                "بالا, پتانسیل خطر بالا و غیرقابل پذیرش",
                            ),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="سطوح هشدار و شدت خطر بالقوه",
                    ),
                ),
                (
                    "owner_report",
                    models.CharField(
                        blank=True,
                        choices=[
                            (
                                "اجرا و نصب خاموش کننده دستی, نشت\u200cیاب گاز, اجرا و اصلاح حفاظ ها و داکت\u200cها و سیم\u200cکشی و کلیه موارد عمومی",
                                "اجرا و نصب خاموش کننده دستی, نشت\u200cیاب گاز, اجرا و اصلاح حفاظ ها و داکت\u200cها و سیم\u200cکشی و کلیه موارد عمومی",
                            ),
                            (
                                "اجرا سیستم اعلام حریق اتومات, علاوه بر موارد سطح ۴",
                                "اجرا سیستم اعلام حریق اتومات, علاوه بر موارد سطح ۴",
                            ),
                            (
                                "اجرای سیستم اطفاء حریق آبی و اجرای شبکه بازنده کل بنا, علاوه بر سطح ۳",
                                "اجرای سیستم اطفاء حریق آبی و اجرای شبکه بازنده کل بنا, علاوه بر سطح ۳",
                            ),
                            (
                                "تمامی موارد ایمنی از جمله خروج دوم, مستقل سازی پلکان و موارد سطوح قبلی در آن لازم الاجرا است",
                                "تمامی موارد ایمنی از جمله خروج دوم, مستقل سازی پلکان و موارد سطوح قبلی در آن لازم الاجرا است",
                            ),
                        ],
                        max_length=255,
                        null=True,
                        verbose_name="سطوح ایمنی و اقدامات مالک/بهره بردار (اعتبار یکساله)",
                    ),
                ),
                (
                    "ready_to_review",
                    models.BooleanField(
                        default=False, verbose_name="بازدید انجام شده است"
                    ),
                ),
                (
                    "approved_by_manager",
                    models.BooleanField(
                        default=False, verbose_name="تایید شده توسط مدیر"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[("done", "انجام شده"), ("pending", "در دست انجام")],
                        default="pending",
                        max_length=20,
                        null=True,
                        verbose_name="وضعیت بازرسی",
                    ),
                ),
                (
                    "inspection_code",
                    models.CharField(
                        blank=True,
                        max_length=12,
                        null=True,
                        unique=True,
                        verbose_name="کد بازرسی",
                    ),
                ),
                (
                    "building",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="building.building",
                        verbose_name="ساختمان",
                    ),
                ),
                (
                    "fire_station",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="management.firestation",
                        verbose_name="آتش نشانی بازرس",
                    ),
                ),
                (
                    "head_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="head_staff",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مسئول بازرسان",
                    ),
                ),
                (
                    "staff",
                    models.ManyToManyField(
                        blank=True, to=settings.AUTH_USER_MODEL, verbose_name="بازرسان"
                    ),
                ),
            ],
            options={
                "verbose_name": "بازرسی",
                "verbose_name_plural": "بازرسی ها",
            },
        ),
    ]
