services:
  db:
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 3s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    command: ["/app/entrypoint.sh"]
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - static:/app/staticfiles
    # (optional) uncomment to debug file perms as root:
    # user: "0:0"

volumes:
  pgdata:
  static:
