# Generated by Django 5.2.4 on 2025-07-29 16:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CheckBoxes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
                (
                    "body",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="متن سوال"
                    ),
                ),
                (
                    "extra_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="توضیحات اضافی"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MarkSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="عنوان"
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="ترتیب")),
                (
                    "questions",
                    models.ManyToManyField(
                        blank=True, to="FormCreator.checkboxes", verbose_name="سوالات"
                    ),
                ),
                (
                    "sub_title",
                    models.ManyToManyField(
                        blank=True,
                        to="FormCreator.marksection",
                        verbose_name="زیر مجموعه سوالات",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SafetyForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام مالک"
                    ),
                ),
                (
                    "renewal_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کد نوسازی"
                    ),
                ),
                (
                    "infrastructure",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کاربری"
                    ),
                ),
                (
                    "address",
                    models.TextField(blank=True, null=True, verbose_name="آدرس دقیق"),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, null=True, verbose_name="تلفن تماس"),
                ),
                (
                    "area",
                    models.FloatField(
                        blank=True, default=0.0, null=True, verbose_name="ربنا"
                    ),
                ),
                (
                    "form",
                    models.ManyToManyField(
                        blank=True, to="FormCreator.marksection", verbose_name="سوالات"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "فرم چک لیست بازدید موارد ایمنی و آتش\u200cنشانی (بهره\u200cبرداری)",
            },
        ),
        migrations.CreateModel(
            name="SafetyFormForEco",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام مالک"
                    ),
                ),
                (
                    "renewal_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کدنوسازی"
                    ),
                ),
                (
                    "infrastructure",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کاربری"
                    ),
                ),
                (
                    "forward_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="شماره ارجاع",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, null=True, verbose_name="شماره تلفن"),
                ),
                (
                    "visisted_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاریخ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "form",
                    models.ManyToManyField(
                        blank=True, to="FormCreator.marksection", verbose_name="سوالات"
                    ),
                ),
                (
                    "staff_visited",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناسان بازدید",
                    ),
                ),
            ],
        ),
    ]
