# Generated by Django 5.2.4 on 2025-07-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="safetyform",
            options={
                "verbose_name_plural": "فرم چک لیست بازدید موارد ایمنی و آتش\u200cنشانی (بهره\u200cبرداری) |  اداره امور ایمنی ساختمان ها"
            },
        ),
        migrations.AlterModelOptions(
            name="safetyformforeco",
            options={
                "verbose_name_plural": "اداره امور ایمنی اصناف و اماکن پرخطر | فرم چک لیست بازید موارد ایمنی و آتش نشانی"
            },
        ),
        migrations.AlterField(
            model_name="safetyform",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="تلفن تماس"
            ),
        ),
        migrations.AlterField(
            model_name="safetyformforeco",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="شماره تلفن"
            ),
        ),
    ]
