# Generated by Django 5.2.4 on 2025-07-29 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0002_alter_safetyform_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SafetyFormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("checked", models.BooleanField(default=False)),
                ("comment", models.TextField(blank=True, null=True)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="responses",
                        to="FormCreator.safetyform",
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="FormCreator.checkboxes",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="FormCreator.marksection",
                    ),
                ),
            ],
            options={
                "unique_together": {("form", "question")},
            },
        ),
    ]
