# Generated by Django 5.2.4 on 2025-07-30 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0003_safetyformresponse"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="safetyformresponse",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="safetyformresponse",
            name="form",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="FormCreator.safetyform"
            ),
        ),
        migrations.CreateModel(
            name="CheckedQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "items",
                    models.ManyToManyField(blank=True, to="FormCreator.checkboxes"),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FormCreator.marksection",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="check_questions",
            field=models.ManyToManyField(blank=True, to="FormCreator.checkedquestion"),
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="checked",
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="comment",
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="question",
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="section",
        ),
    ]
