# Generated by Django 5.2.4 on 2025-07-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0004_alter_safetyformresponse_unique_together_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyform",
            name="address",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="area",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="infrastructure",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="renewal_code",
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="address",
            field=models.TextField(blank=True, null=True, verbose_name="آدرس دقیق"),
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="area",
            field=models.FloatField(
                blank=True, default=0.0, null=True, verbose_name="ربنا"
            ),
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="infrastructure",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کاربری"
            ),
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="owner_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="نام مالک"
            ),
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="تلفن تماس"
            ),
        ),
        migrations.AddField(
            model_name="safetyformresponse",
            name="renewal_code",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="کد نوسازی"
            ),
        ),
    ]
