# Generated by Django 5.2.4 on 2025-07-30 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "FormCreator",
            "0005_remove_safetyform_address_remove_safetyform_area_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="description",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="forward_number",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="infrastructure",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="owner_name",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="renewal_code",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="staff_visited",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="visisted_date",
        ),
        migrations.CreateModel(
            name="SafetyFormForEcoResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام مالک"
                    ),
                ),
                (
                    "renewal_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کدنوسازی"
                    ),
                ),
                (
                    "infrastructure",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کاربری"
                    ),
                ),
                (
                    "forward_number",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="شماره ارجاع",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="شماره تلفن"
                    ),
                ),
                (
                    "visisted_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="تاریخ"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "check_questions",
                    models.ManyToManyField(
                        blank=True, to="FormCreator.checkedquestion"
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="FormCreator.safetyformforeco",
                    ),
                ),
                (
                    "staff_visited",
                    models.ManyToManyField(
                        blank=True,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارشناسان بازدید",
                    ),
                ),
            ],
        ),
    ]
