# Generated by Django 5.2.4 on 2025-08-09 10:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0006_remove_safetyformforeco_description_and_more"),
        ("building", "0004_remove_building_safety_form_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("body", models.CharField(max_length=255)),
                ("extra_description", models.TextField(blank=True)),
                ("required", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["section_id", "order", "id"],
            },
        ),
        migrations.RemoveField(
            model_name="marksection",
            name="questions",
        ),
        migrations.RemoveField(
            model_name="checkedquestion",
            name="items",
        ),
        migrations.RemoveField(
            model_name="checkedquestion",
            name="section",
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="check_questions",
        ),
        migrations.RemoveField(
            model_name="safetyformforecoresponse",
            name="check_questions",
        ),
        migrations.RemoveField(
            model_name="marksection",
            name="sub_title",
        ),
        migrations.RemoveField(
            model_name="safetyformforeco",
            name="form",
        ),
        migrations.RemoveField(
            model_name="safetyform",
            name="form",
        ),
        migrations.RemoveField(
            model_name="safetyformresponse",
            name="form",
        ),
        migrations.RemoveField(
            model_name="safetyformforecoresponse",
            name="form",
        ),
        migrations.RemoveField(
            model_name="safetyformforecoresponse",
            name="staff_visited",
        ),
        migrations.CreateModel(
            name="FormTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("ECO", "Eco")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "-version"],
                "unique_together": {("name", "version")},
            },
        ),
        migrations.CreateModel(
            name="FormResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("owner_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "renewal_code",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "infrastructure",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("area", models.FloatField(blank=True, null=True)),
                (
                    "forward_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("visited_date", models.DateTimeField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "staff_visited",
                    models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="responses",
                        to="FormCreator.formtemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="SectionResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_snapshot", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "form_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="section_responses",
                        to="FormCreator.formresponse",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="FormCreator.sectionresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["parent__id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ItemResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body_snapshot", models.CharField(max_length=255)),
                ("extra_description_snapshot", models.TextField(blank=True)),
                (
                    "answer",
                    models.CharField(
                        choices=[
                            ("YES", "Yes"),
                            ("NO", "No"),
                            ("NA", "N/A"),
                            ("UNANSWERED", "Unanswered"),
                        ],
                        default="UNANSWERED",
                        max_length=12,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "item_template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="FormCreator.itemtemplate",
                    ),
                ),
                (
                    "section_response",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="FormCreator.sectionresponse",
                    ),
                ),
            ],
            options={
                "ordering": ["section_response_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="SectionTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=1)),
                ("title", models.CharField(max_length=255)),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="FormCreator.formtemplate",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="FormCreator.sectiontemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["parent__id", "order", "id"],
            },
        ),
        migrations.AddField(
            model_name="sectionresponse",
            name="section_template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="FormCreator.sectiontemplate",
            ),
        ),
        migrations.AddField(
            model_name="itemtemplate",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="FormCreator.sectiontemplate",
            ),
        ),
        migrations.DeleteModel(
            name="CheckBoxes",
        ),
        migrations.DeleteModel(
            name="CheckedQuestion",
        ),
        migrations.DeleteModel(
            name="MarkSection",
        ),
        migrations.DeleteModel(
            name="SafetyForm",
        ),
        migrations.DeleteModel(
            name="SafetyFormResponse",
        ),
        migrations.DeleteModel(
            name="SafetyFormForEco",
        ),
        migrations.DeleteModel(
            name="SafetyFormForEcoResponse",
        ),
    ]
