# Generated by Django 5.2.4 on 2025-07-28 17:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="نام مالک"
                    ),
                ),
                (
                    "renewal_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="کد نوسازی"
                    ),
                ),
                (
                    "fire_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "کم خطر"),
                            ("moderate", "میان خطر"),
                            ("dangerous", "پرخطر"),
                            ("very_dangerous", "بسیار پر خطر"),
                        ],
                        max_length=15,
                        null=True,
                        verbose_name="خطر حریق",
                    ),
                ),
                (
                    "incident_risk",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unsafe", "ناایمن"),
                            ("low_safety", "ایمنی پایین"),
                            ("fairly_safe", "نسبتا ایمن"),
                        ],
                        max_length=12,
                        null=True,
                        verbose_name="خطر حادثه",
                    ),
                ),
                (
                    "permanant_residence",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="تعداد ساکنان دائمی",
                    ),
                ),
                (
                    "temp_residence",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="تعداد ساکنان موقت",
                    ),
                ),
                ("is_building_tall", models.BooleanField(blank=True, null=True)),
                ("width", models.FloatField(default=0.0, verbose_name="طول")),
                ("height", models.FloatField(default=0.0, verbose_name="ارتفاع")),
                ("length", models.FloatField(default=0.0, verbose_name="عرض")),
                ("area", models.FloatField(default=0.0, verbose_name="مساحت")),
                (
                    "access_problem",
                    models.TextField(
                        blank=True, null=True, verbose_name="مشکلات دسترسی"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="توضیحات"),
                ),
                (
                    "building_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("tradeAssociations", "واحد صنفی"),
                            ("accommodationUnit", "واحد اقامتی"),
                            ("treatmentUnit", "واحد درمانی"),
                            ("militaryUnit", "واحد نظامی"),
                            ("residentialUnit", "واحد مسکونی"),
                            ("businessUnit", "واحد تجاری"),
                            ("industrialUnit", "واحد صنعتی"),
                            ("administrativeUnit", "واحد اداری"),
                            ("educationalUnit", "واحد آموزشی"),
                            ("warehouse", "انبار"),
                            ("other", "سایر"),
                        ],
                        max_length=30,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("checked", "مشاهده شد"),
                            ("filled", "پر شده است"),
                            ("not_working", "کار نمی\u200cکند"),
                            ("out_dated", "تاریخ گذشته"),
                        ],
                        max_length=12,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Floor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order_of_floor",
                    models.IntegerField(default=0, verbose_name="شماره طبقه"),
                ),
                ("width", models.FloatField(default=0.0)),
                ("height", models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name="ImageHandler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageUploader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="building/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpeg", "jpg", "png", "webp", "ico"]
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("icon", models.URLField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Widget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("icon", models.URLField(blank=True, max_length=500, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
