# Generated by Django 5.2.4 on 2025-07-28 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("building", "0001_initial"),
        ("management", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.location",
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="equipments",
            field=models.ManyToManyField(blank=True, to="building.equipment"),
        ),
        migrations.AddField(
            model_name="floor",
            name="shape",
            field=models.ManyToManyField(blank=True, to="management.location"),
        ),
        migrations.AddField(
            model_name="building",
            name="floors",
            field=models.ManyToManyField(blank=True, to="building.floor"),
        ),
        migrations.AddField(
            model_name="floor",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="building.imagehandler", verbose_name="عکس  های طبقه"
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="images",
            field=models.ManyToManyField(
                blank=True, to="building.imagehandler", verbose_name="عکس های ساختمان"
            ),
        ),
        migrations.AddField(
            model_name="route",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.location",
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="routes",
            field=models.ManyToManyField(blank=True, to="building.route"),
        ),
        migrations.AddField(
            model_name="building",
            name="routes",
            field=models.ManyToManyField(blank=True, to="building.route"),
        ),
        migrations.AddField(
            model_name="widget",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="management.location",
            ),
        ),
        migrations.AddField(
            model_name="floor",
            name="widget",
            field=models.ManyToManyField(blank=True, to="building.widget"),
        ),
        migrations.AddField(
            model_name="equipment",
            name="widget",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="building.widget",
            ),
        ),
    ]
