# Generated by Django 5.2.4 on 2025-07-31 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0006_remove_safetyformforeco_description_and_more"),
        ("building", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="safety_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="FormCreator.safetyformresponse",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="safety_form_for_eco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="FormCreator.safetyformforecoresponse",
            ),
        ),
    ]
