# Generated by Django 5.2.4 on 2025-08-09 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("building", "0003_building_safety_form_building_safety_form_for_eco"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="building",
            name="safety_form",
        ),
        migrations.RemoveField(
            model_name="building",
            name="safety_form_for_eco",
        ),
    ]
