# Generated by Django 5.2.4 on 2025-08-09 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FormCreator", "0007_itemtemplate_remove_marksection_questions_and_more"),
        ("building", "0004_remove_building_safety_form_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="building",
            name="safety_form",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_form",
                to="FormCreator.formresponse",
            ),
        ),
        migrations.AddField(
            model_name="building",
            name="safety_form_for_eco",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="safety_form_for_eco",
                to="FormCreator.formresponse",
            ),
        ),
    ]
